allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp

onlyBuiltDependencies:
  - bcrypt
